-- 코드를 입력하세요

with CTE as (
    SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE, S.SALES as TOTAL_SALES
        FROM BOOK AS B JOIN 
            (SELECT BOOK_ID, SUM(SALES) as SALES FROM BOOK_SALES 
            WHERE SALES_DATE like '2022-01%'
            GROUP BY BOOK_ID) as S on B.BOOK_ID = S.BOOK_ID

)

SELECT B.AUTHOR_ID,	A.AUTHOR_NAME,	B.CATEGORY,     
            SUM(B.PRICE * B.TOTAL_SALES) as TOTAL_SALE 
     FROM CTE AS B JOIN AUTHOR AS A on B.AUTHOR_ID = A.AUTHOR_ID
      GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC