-- 코드를 작성해주세요

SELECT ED.ID, (SELECT COUNT(*) FROM ECOLI_DATA WHERE PARENT_ID = ED.ID) AS CHILD_COUNT 
FROM ECOLI_DATA as ED
ORDER BY ID ASC



# SELECT P.ID, COUNT(C.ID) AS CHILD_COUNT
# FROM ECOLI_DATA P
# LEFT JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
# GROUP BY P.ID;
# ORDER BY ID ASC