-- 코드를 입력하세요
SELECT P.PRODUCT_CODE,	
       (P.PRICE * SUM(S.SALES_AMOUNT)) as SALES 

FROM PRODUCT as P
    JOIN OFFLINE_SALE as S on P.PRODUCT_ID = S.PRODUCT_ID
    
GROUP BY P.PRODUCT_ID

ORDER BY 2 desc, 1 asc