-- 코드를 입력하세요
SELECT 
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE,	
    PRODUCT_ID,	
    USER_ID,
    SALES_AMOUNT 

from ONLINE_SALE 

WHERE SALES_DATE like '2022-03%'

UNION ALL

SELECT 
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE,
    PRODUCT_ID,	
    NULL AS USER_ID,	
    SALES_AMOUNT 

from OFFLINE_SALE 

WHERE SALES_DATE like '2022-03%'

ORDER BY SALES_DATE asc, PRODUCT_ID asc, USER_ID asc