-- 코드를 입력하세요

WITH NOVEMBER as (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE (START_DATE <= '2022-11-30' and
           END_DATE >= '2022-11-01')
),
DISCOUNT as (
    SELECT CAR_TYPE, 
       (100 - REPLACE(DISCOUNT_RATE, '%', '')) / 100 as DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
),
THIRTY as (
    SELECT CAR_ID 
    
    FROM CAR_RENTAL_COMPANY_CAR as C
        JOIN DISCOUNT as D
            ON C.CAR_TYPE = D.CAR_TYPE

    WHERE C.DAILY_FEE * 30 * D.DISCOUNT_RATE >= 500000 and
        C.DAILY_FEE * 30 * D.DISCOUNT_RATE <   2000000
)

SELECT C.CAR_ID, C.CAR_TYPE,
    TRUNCATE(C.DAILY_FEE * 30 * D.DISCOUNT_RATE, 0) as FEE
    
FROM CAR_RENTAL_COMPANY_CAR as C
    JOIN DISCOUNT as D
        ON C.CAR_TYPE = D.CAR_TYPE
        
WHERE C.CAR_TYPE in ('세단', 'SUV') and
      C.CAR_ID  not in (SELECT CAR_ID FROM NOVEMBER) and
      C.CAR_ID in (SELECT CAR_ID FROM THIRTY)

ORDER BY 3 desc, 2 asc, 1 desc