-- 코드를 입력하세요
WITH CTE as (
    SELECT *, (RANK() over (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC)) as rnk from REST_INFO
)

SELECT FOOD_TYPE,	REST_ID,	REST_NAME,	FAVORITES FROM CTE
    WHERE RNK = 1
    ORDER BY FOOD_TYPE DESC