with CTE as (
    SELECT WRITER_ID FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
        HAVING COUNT(WRITER_ID) >= 3
)

SELECT  USER_ID,	
        NICKNAME,	
        CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) as '전체주소',	
        CONCAT(LEFT(TLNO,3), '-', MID(TLNO,4,4), '-', RIGHT(TLNO,4)) as '전화번호'

FROM USED_GOODS_USER 

WHERE USER_ID in (SELECT * FROM CTE)

ORDER BY 1 desc