-- 코드를 입력하세요

WITH TWENTY_ONE as (
    SELECT USER_ID FROM USER_INFO
    WHERE YEAR(JOINED) = 2021 
),
CTE as (
    SELECT  YEAR(SALES_DATE) as YEAR,
            MONTH(SALES_DATE) as MONTH,
            COUNT(distinct USER_ID) as PURCHASED_USERS,
            ROUND(COUNT(distinct USER_ID) / (SELECT COUNT(USER_ID) FROM TWENTY_ONE), 1) as PURCHASED_RATIO

    FROM ONLINE_SALE
    WHERE USER_ID in (SELECT USER_ID FROM TWENTY_ONE)
    GROUP BY YEAR, MONTH   
)

SELECT * FROM CTE

GROUP BY YEAR, MONTH
ORDER BY 1 asc, 2 asc