-- 코드를 입력하세요

with 
    CTE as (
        SELECT CAR_ID, '대여중' as AVAILABILITY from CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= '2022-10-16' and END_DATE >= '2022-10-16'
            GROUP BY CAR_ID
    ),
    CTE2 as (    
        SELECT CAR_ID, '대여 가능' as AVAILABILITY from CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE CAR_ID not in (SELECT CAR_ID FROM CTE)
            GROUP BY CAR_ID
    ) 


SELECT CAR_ID,	AVAILABILITY FROM CTE
UNION ALL
SELECT CAR_ID,	AVAILABILITY FROM CTE2
ORDER BY CAR_ID DESC