-- 코드를 입력하세요
SELECT P.PRODUCT_ID,
        P.PRODUCT_NAME,
        (P.PRICE * SUM(O.AMOUNT)) as TOTAL_SALES
FROM FOOD_PRODUCT as P
    JOIN FOOD_ORDER as O on P.PRODUCT_ID = O.PRODUCT_ID
    
WHERE O.PRODUCE_DATE like '2022-05%'

GROUP BY P.PRODUCT_ID

ORDER BY 3 desc, 1 asc