-- 코드를 입력하세요



SELECT 
    HOUR(DATETIME) as HOUR, 
    COUNT(*) as COUNT
    #HOUR,	
    #() as COUNT
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) BETWEEN 9 and 19 
    GROUP BY HOUR(DATETIME)
    ORDER BY 1 asc