-- 코드를 입력하세요
with CTE as (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 2 desc limit 1
)


SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE

FROM MEMBER_PROFILE as P 
    JOIN REST_REVIEW as R on P.MEMBER_ID = R.MEMBER_ID
    
    WHERE P.MEMBER_ID in (SELECT MEMBER_ID FROM CTE)
    
    ORDER BY 3 asc, 2 asc