-- 코드를 작성해주세요
SELECT C.ID,	C.GENOTYPE,	P.GENOTYPE as PARENT_GENOTYPE 
from ECOLI_DATA as C 
    LEFT JOIN ECOLI_DATA AS P 
        on C.PARENT_ID = P.ID
    WHERE (C.GENOTYPE | P.GENOTYPE) = C.GENOTYPE 
    ORDER BY ID asc