-- 코드를 작성해주세요


SELECT ID,	EMAIL,	FIRST_NAME,	LAST_NAME from DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES where name = 'Python') or SKILL_CODE & (SELECT CODE FROM SKILLCODES where name = 'C#')
order by ID