-- 코드를 작성해주세요
WITH 
CTE as (
    SELECT *, YEAR(DIFFERENTIATION_DATE) as YEAR FROM ECOLI_DATA
),
MX as (
    SELECT YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE FROM CTE
        GROUP BY YEAR
)

SELECT C.YEAR, 
    (M.MAX_SIZE - C.SIZE_OF_COLONY) as YEAR_DEV,
    C.ID 
        from CTE as C 
        INNER join MX as M on C.YEAR = M.YEAR

ORDER BY YEAR ASC, YEAR_DEV ASC

# 더 간결한 풀이
# SELECT 
#     YEAR(DIFFERENTIATION_DATE) AS YEAR,
#     (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
#     ID
# FROM ECOLI_DATA
# ORDER BY YEAR ASC, YEAR_DEV ASC;