with OCT as (
    SELECT distinct CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE MONTH(START_DATE) = 10
)

SELECT distinct C.CAR_ID FROM CAR_RENTAL_COMPANY_CAR as C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as H on C.CAR_ID = H.CAR_ID

WHERE C.CAR_TYPE = '세단' and
    C.CAR_ID in (SELECT * FROM OCT)
ORDER BY 1 desc