-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE from USED_GOODS_BOARD as B inner join USED_GOODS_REPLY as R on B.BOARD_ID = R.BOARD_ID 
WHERE B.CREATED_DATE like '2022-10%' 
order by R.CREATED_DATE asc, B.TITLE asc