-- 코드를 입력하세요
SELECT B.BOOK_ID,	A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE 

FROM BOOK as B JOIN AUTHOR as A on A.AUTHOR_ID = B.AUTHOR_ID

WHERE B.CATEGORY = '경제'

ORDER BY 3 asc